import 'package:flutter/material.dart';
import 'package:search_anchor_picker/src/picker_config.dart';
import 'package:search_anchor_picker/src/picker_status.dart';
import 'package:search_anchor_picker/src/raw/search_anchor_picker.dart';
import 'package:search_anchor_picker/src/related_list_item.dart';

export 'package:search_anchor_picker/src/raw/search_anchor_picker.dart'
    show GenericRawSearchAnchorPicker, RawSearchAnchorPicker;

/// SearchAnchor-like picker with related-list status and nested popup support.
class GenericSearchAnchorPicker<T, K>
    extends GenericRawSearchAnchorPicker<T, K> {
  // `selectionMode` is captured for the default related-list item builder.
  // ignore: use_super_parameters
  GenericSearchAnchorPicker({
    required GenericPickerConfig<T, K> config,
    required super.initialSelectedIds,
    super.key,
    SelectionMode selectionMode = SelectionMode.multi,
    super.onChange,
    super.onClose,
    super.closeSavingBuilder,
    super.closeSaveFailedBuilder,
    super.searchController,
    super.triggerBuilder,
    super.triggerChild,
    super.iconWhenEmpty,
    super.iconWhenSelected,
    super.iconSize,
    super.headerBuilder,
    super.headerTiles,
    super.selectedFirst,
    super.closeQueryBehavior,
    Widget Function(
      BuildContext context,
      T item,
      bool isSelected,
      PickerRelatedListItemStatus relatedListItemStatus,
      VoidCallback toggle,
    )?
    itemBuilder,
    super.resultsBuilder,
    super.searchFieldBuilder,
    super.loadingBuilder,
    super.emptyBuilder,
    super.emptyText,
    super.noResultsText,
    super.errorBuilder,
    super.viewBuilder,
    super.viewSurfaceBuilder,
    super.menuOffset,
    super.menuOffsetAnimationDuration,
    super.isFullScreen,
    super.viewLeading,
    super.viewTrailing,
    super.viewHintText,
    super.viewBackgroundColor,
    super.viewElevation,
    super.viewSurfaceTintColor,
    super.viewSide,
    super.viewShape,
    super.viewBarPadding,
    super.headerHeight,
    super.headerTextStyle,
    super.headerHintStyle,
    super.dividerColor,
    super.viewConstraints,
    super.viewPadding,
    super.shrinkWrap,
    super.textCapitalization,
    super.viewOnChanged,
    super.viewOnSubmitted,
    super.viewOnClose,
    super.viewOnOpen,
    super.textInputAction,
    super.keyboardType,
    super.enabled,
    super.smartDashesType,
    super.smartQuotesType,
  }) : super(
         config: config,
         selectionMode: selectionMode,
         isSelectable: (item) => relatedListIsSelectable(config, item),
         canUnselect: (context, item) {
           return relatedListCanUnselect(context, config, item);
         },
         itemBuilder: relatedListRowBuilder(config, selectionMode, itemBuilder),
       );
}

class SearchAnchorPicker<T> extends GenericSearchAnchorPicker<T, int> {
  SearchAnchorPicker({
    required super.config,
    required super.initialSelectedIds,
    super.key,
    super.selectionMode,
    super.onChange,
    super.onClose,
    super.closeSavingBuilder,
    super.closeSaveFailedBuilder,
    super.searchController,
    super.triggerBuilder,
    super.triggerChild,
    super.iconWhenEmpty,
    super.iconWhenSelected,
    super.iconSize,
    super.headerBuilder,
    super.headerTiles,
    super.selectedFirst,
    super.closeQueryBehavior,
    super.itemBuilder,
    super.resultsBuilder,
    super.searchFieldBuilder,
    super.loadingBuilder,
    super.emptyBuilder,
    super.emptyText,
    super.noResultsText,
    super.errorBuilder,
    super.viewBuilder,
    super.viewSurfaceBuilder,
    super.menuOffset,
    super.menuOffsetAnimationDuration,
    super.isFullScreen,
    super.viewLeading,
    super.viewTrailing,
    super.viewHintText,
    super.viewBackgroundColor,
    super.viewElevation,
    super.viewSurfaceTintColor,
    super.viewSide,
    super.viewShape,
    super.viewBarPadding,
    super.headerHeight,
    super.headerTextStyle,
    super.headerHintStyle,
    super.dividerColor,
    super.viewConstraints,
    super.viewPadding,
    super.shrinkWrap,
    super.textCapitalization,
    super.viewOnChanged,
    super.viewOnSubmitted,
    super.viewOnClose,
    super.viewOnOpen,
    super.textInputAction,
    super.keyboardType,
    super.enabled,
    super.smartDashesType,
    super.smartQuotesType,
  });
}
