import 'package:build/build.dart';
import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:glob/glob.dart';

/// Reads `/*source:tag*/` … `/*source-end:tag*/` from library sources and
/// writes `exampleSources` with `code_builder`.
class ExampleSourceBuilder implements Builder {
  const ExampleSourceBuilder();

  @override
  Map<String, List<String>> get buildExtensions => const {
    r'$lib$': ['card_gallery/example_sources.g.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final ids = await buildStep.findAssets(Glob('lib/**.dart')).toList();
    ids.sort((a, b) => a.path.compareTo(b.path));
    final regions = <String, List<String>>{};
    for (final id in ids) {
      if (id.path.endsWith('.g.dart')) continue;
      if (id.path.endsWith('example_source.dart')) continue;
      _collect(await buildStep.readAsString(id), regions);
    }
    final prepared = <String, String>{
      for (final entry in regions.entries)
        entry.key: prepareExampleSource(entry.value.join('\n')),
    };
    final library = Library(
      (b) => b
        ..comments.add('Generated by example_source_builder. Do not edit.')
        ..body.add(
          Field(
            (field) => field
              ..name = 'exampleSources'
              ..modifier = FieldModifier.constant
              ..type = refer('Map<String, String>')
              ..assignment = Code(_mapLiteral(prepared)),
          ),
        ),
    );
    final emitter = DartEmitter(useNullSafetySyntax: true);
    final formatted = DartFormatter(
      languageVersion: DartFormatter.latestLanguageVersion,
    ).format('${library.accept(emitter)}\n');
    await buildStep.writeAsString(
      AssetId(
        buildStep.inputId.package,
        'lib/card_gallery/example_sources.g.dart',
      ),
      formatted,
    );
  }
}

String _mapLiteral(Map<String, String> values) {
  final buffer = StringBuffer('<String, String>{\n');
  for (final entry in values.entries) {
    buffer.writeln("  '${entry.key}': ${_rawTriple(entry.value)},");
  }
  buffer.write('}');
  return buffer.toString();
}

String _rawTriple(String value) {
  if (value.contains("'''")) {
    throw StateError('Example source contains a raw triple quote');
  }
  return "r'''$value'''";
}

void _collect(String file, Map<String, List<String>> regions) {
  final block = RegExp(
    r'/\*source:([^*]+)\*/([\s\S]*?)/\*source-end:\1\*/',
  );
  for (final match in block.allMatches(file)) {
    regions.putIfAbsent(match.group(1)!, () => []).add(match.group(2)!);
  }
  final lines = file.split('\n');
  for (var i = 0; i < lines.length; i++) {
    final open = RegExp(r'^\s*// source:(\S+)\s*$').firstMatch(lines[i]);
    if (open == null) continue;
    final tag = open.group(1)!;
    final body = <String>[];
    i++;
    while (i < lines.length &&
        !RegExp('^\\s*// source-end:$tag\\s*\$').hasMatch(lines[i])) {
      final line = lines[i];
      final commented = RegExp(r'^\s*// ?(.*)$').firstMatch(line);
      body.add(commented?.group(1) ?? line);
      i++;
    }
    regions.putIfAbsent(tag, () => []).add(body.join('\n'));
  }
}

/// Dedents a region and keeps bold markers attached to the following line.
String prepareExampleSource(String source) {
  return _attachMarkerLines(_dedent(source));
}

String _attachMarkerLines(String source) {
  const markers = ['/*bold=on*/', '/*bold=off*/'];
  final kept = <String>[];
  var pending = '';
  for (final line in source.split('\n')) {
    if (markers.contains(line.trim())) {
      pending = '$pending${line.trim()}';
      continue;
    }
    kept.add('$pending$line');
    pending = '';
  }
  if (pending.isNotEmpty) kept.add(pending);
  return kept.join('\n');
}

String _dedent(String source) {
  final lines = source.split('\n');
  while (lines.isNotEmpty && lines.first.trim().isEmpty) {
    lines.removeAt(0);
  }
  while (lines.isNotEmpty && lines.last.trim().isEmpty) {
    lines.removeLast();
  }
  var indent = 1 << 30;
  for (final line in lines) {
    if (line.trim().isEmpty) continue;
    final width = line.length - line.trimLeft().length;
    if (width < indent) indent = width;
  }
  if (indent == 1 << 30 || indent == 0) return lines.join('\n');
  return [
    for (final line in lines)
      line.length >= indent ? line.substring(indent) : line,
  ].join('\n');
}
