// Generated by example_source_builder. Do not edit.

const Map<String, String> exampleSources = <String, String>{
  'close-save-multi': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Close save, multi'),
  initialSelectedIds: selected.toList(),
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'change-save-multi': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Change save, multi'),
  initialSelectedIds: selected.toList(),
  onChange: (delta) {
    selected
      ..addAll(delta.added)
      ..removeAll(delta.removed);
  },
);''',
  'single-required': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Single required'),
  initialSelectedIds: selected.toList(),
  selectionMode: SelectionMode.single,
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'single-optional': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Single optional'),
  initialSelectedIds: selected.toList(),
  selectionMode: SelectionMode.singleOptional,
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'selected-first': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Selected first', selectedFirst: true),
  initialSelectedIds: selected.toList(),
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'catalog-order': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Catalog order', selectedFirst: false),
  initialSelectedIds: selected.toList(),
  selectedFirst: false,
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'inactive-rows': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    title: 'Inactive rows',
    relatedListItemStatusOf: (person) =>
        PickerRelatedListItemStatus(selectable: !person.locked),
  ),
  initialSelectedIds: selected.toList(),
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'inactive-rows-plus-onchange': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    relatedListItemStatusOf: (person) =>
        PickerRelatedListItemStatus(selectable: !person.locked),
  ),
  onChange: (delta) { /* write selected */ },
);''',
  'related-list-icons':
      r'''itemBuilder: (context, person, selected, status, source, toggle) {
  return DefaultPickerItemTile(
    selected: selected,
    relatedListItemStatus: status,
    onToggle: (_) => toggle(),
    title: Text(person.name),
    subtitle: Text(person.team),
    selectionMode: SelectionMode.multi,
  );
}''',
  'in-use-confirm': r'''PickerConfig<Person>(
  relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
    unselectPolicy: directory.contains(person.id)
        ? PickerUnselectPolicy.confirm
        : PickerUnselectPolicy.allow,
  ),
);''',
  'bulk-select-clear-search-results': r'''SearchAnchorPicker<Person>(
  onChange: (delta) async {
    await api.updateMembers(added: delta.added, removed: delta.removed);
  },
  headerBuilder: (context, controller, items) => [
    TextButton(
      onPressed: controller.selectFiltered,
      child: const Text('Select results'),
    ),
    TextButton(
      onPressed: controller.clearFiltered,
      child: const Text('Clear results'),
    ),
  ],
);''',
  'bulk-select-clear-all-loaded-not-just-filtered':
      r'''headerBuilder: (context, controller, items) => [
  TextButton(
    onPressed: controller.selectLoaded,
    child: const Text('Select loaded'),
  ),
  TextButton(
    onPressed: controller.clearLoaded,
    child: const Text('Clear loaded'),
  ),
],''',
  'bulk-onclose': r'''SearchAnchorPicker<Person>(
  viewConstraints: const BoxConstraints(
    minWidth: 560,
    maxWidth: 640,
    minHeight: 320,
    maxHeight: 520,
  ),
  onClose: (result) { /* one net write */ },
  headerBuilder: (context, controller, items) => [
    GridView.count(
      crossAxisCount: 4,
      shrinkWrap: true,
      children: [
        OutlinedButton(
          onPressed: controller.selectFiltered,
          child: const Text('Select results'),
        ),
        OutlinedButton(
          onPressed: controller.clearFiltered,
          child: const Text('Clear results'),
        ),
        OutlinedButton(
          onPressed: controller.selectLoaded,
          child: const Text('Select loaded'),
        ),
        OutlinedButton(
          onPressed: controller.clearLoaded,
          child: const Text('Clear loaded'),
        ),
      ],
    ),
  ],
);''',
  'bulk-skips-inactive-rows': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    relatedListItemStatusOf: (person) =>
        PickerRelatedListItemStatus(selectable: !person.locked),
  ),
  onChange: (delta) { /* write selected */ },
  headerBuilder: (context, controller, items) => [
    TextButton(
      onPressed: controller.selectFiltered,
      child: const Text('Select results'),
    ),
    TextButton(
      onPressed: controller.selectLoaded,
      child: const Text('Select loaded'),
    ),
  ],
);''',
  'unrelated-child-bulk-commands': r'''SubPickerTile<Person>(
  title: 'Directory',
  onChange: (delta, notifyParent) { /* write the whole delta once */ },
  headerBuilder: (context, controller, items) => [
    TextButton(
      onPressed: controller.selectFiltered,
      child: const Text('Select results'),
    ),
    TextButton(
      onPressed: controller.clearFiltered,
      child: const Text('Clear results'),
    ),
  ],
);''',
  'full-screen-popup': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'Full-screen popup'),
  initialSelectedIds: selected.toList(),
  isFullScreen: true,
  onClose: (result) { /* write selected */ },
);''',
  'unrelated-anchored-nested-popups': r'''SearchAnchorPicker<Person>(
  isFullScreen: false,
  viewConstraints: const BoxConstraints(
    minWidth: 360,
    maxWidth: 420,
    minHeight: 320,
    maxHeight: 480,
  ),
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory membership',
      menuOffset: const Offset(24, 36),
      viewConstraints: const BoxConstraints(
        minWidth: 240,
        maxWidth: 280,
        minHeight: 200,
        maxHeight: 280,
      ),
    ),
    SubPickerTile<Person>(
      title: 'Watchlist',
      menuOffset: const Offset(56, 12),
      viewConstraints: const BoxConstraints(
        minWidth: 360,
        maxWidth: 440,
        minHeight: 300,
        maxHeight: 420,
      ),
    ),
  ],
);''',
  'custom-empty-copy': r'''SearchAnchorPicker<Person>(
  emptyText: 'Custom: No items',
  noResultsText: 'Custom: No results',
  onClose: (result) { /* write selected */ },
);''',
  'multiline-field': r'''SearchAnchorPicker<Person>(
  initialSelectedIds: const [1, 3, 4, 6, 7, 8, 9, 10, 11, 12],
  onClose: (result) { /* write selected */ },
);''',
  'field-without-chips': r'''SearchAnchorPicker<Person>(
  triggerBuilder: (context, open, _) => DefaultPickerFieldTrigger<int>(
    selectedIds: selected,
    labelOf: (id) => names[id] ?? '#$id',
    onOpen: open,
    onDeleted: selected.remove,
    showChips: false,
  ),
  onClose: (result) { /* write selected */ },
);''',
  'custom-saving-wrap': r'''SearchAnchorPicker<Person>(
  onClose: (result) async {
    await Future<void>.delayed(const Duration(milliseconds: 1200));
    // write selected
  },
  closeSavingBuilder: (context, child) => Stack(
    children: [
      IgnorePointer(child: child),
      const Positioned.fill(
        child: ColoredBox(color: Color(0x73000000)),
      ),
      const Center(
        child: Material(
          child: Padding(
            padding: EdgeInsets.all(24),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                CircularProgressIndicator(),
                SizedBox(height: 16),
                Text('Writing members…'),
              ],
            ),
          ),
        ),
      ),
    ],
  ),
);''',
  'selected-stay-in-this-open-list': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    itemsLoader: (_, _) async {
      final catalog = people.where((p) => p.id <= 6).toList();
      final extra = people.where(
        (p) => selected.contains(p.id) && p.id > 6,
      );
      return [...extra, ...catalog];
    },
  ),
  initialSelectedIds: selected.toList(),
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'direct-sublist-uncheck-leaves-the-parent': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    itemsLoader: (_, _) async =>
        people.where((p) => sublistUnion.contains(p.id)).toList(),
    reloadKey: {...sublistUnion},
  ),
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory',
      parentController: controller,
      parentSelectionEffect: SubPickerParentSelectionEffect.mirror,
    ),
    SubPickerTile<Person>(title: 'Watchlist', /* same effect */),
    SubPickerTile<Person>(title: 'Team', /* same effect */),
  ],
);''',
  'direct-parent-checked-stays': r'''onChange: (delta) {
  final unionBefore = {...sublistUnion};
  final pendingNow = {...parent.pendingIds};
  writeSublist(delta);
  final stay = {
    for (final id in pendingNow)
      if (fieldSelected.contains(id) || !unionBefore.contains(id)) id,
  };
  parent.syncPending(
    added: delta.added,
    removed: delta.removed.where((id) => !stay.contains(id)),
  );
},''',
  'reverse-parent-check-appears-in-sublists': r'''SubPickerTile<Person>(
  config: peopleConfig(
    itemsLoader: (_, _) async => people
        .where((p) =>
            catalog.contains(p.id) && parent.pendingIds.contains(p.id))
        .toList(),
    listenable: parent.pendingIdsListenable,
  ),
);''',
  'reverse-parent-check-unlocks-sublists': r'''SubPickerTile<Person>(
  config: peopleConfig(
    relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
      selectable: parent.pendingIds.contains(person.id),
    ),
    relatedListItemStatusListenable: parent.pendingIdsListenable,
  ),
);''',
  'unrelated-sublists-in-the-card-subtitle':
      r'''headerBuilder: (context, controller, items) => [
  SubPickerTile<Person>(
    title: 'Directory',
    onChange: (delta, notifyParent) { writeDirectory(delta); },
  ),
  SubPickerTile<Person>(
    title: 'Watchlist',
    onChange: (delta, notifyParent) { writeWatchlist(delta); },
  ),
  SubPickerTile<Person>(
    title: 'Team',
    onChange: (delta, notifyParent) { writeTeam(delta); },
  ),
];''',
  'unrelated-shared-field':
      r'''void writeSublist(Set<int> ids, PickerDelta<int> delta) {
  applyDelta(ids, delta); // same persist as the child onChange
}

SubPickerTile<Person>(
  onChange: (delta, notifyParent) => writeSublist(watchlist, delta),
);
// Chip X:
writeSublist(watchlist, PickerDelta(removed: {id}));''',
  'unrelated-block-unselect-while-on-parent':
      r'''relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
  unselectPolicy: parent.pendingIds.contains(person.id)
      ? PickerUnselectPolicy.blocked
      : PickerUnselectPolicy.allow,
),''',
  'unrelated-confirm-unselect-while-on-parent':
      r'''unselectPolicy: parent.pendingIds.contains(person.id)
    ? PickerUnselectPolicy.confirm
    : PickerUnselectPolicy.allow,''',
  'unrelated-nested-directory': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'People'),
  initialSelectedIds: selected.toList(),
  onClose: (result) { /* write selected */ },
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory membership',
      config: directoryConfig,
      initialSelectedIds: directory.toList(),
      onClose: (result) { /* write directory */ },
    ),
  ],
);''',
  'unrelated-sibling-sublists':
      r'''headerBuilder: (context, controller, items) => [
  SubPickerTile<Person>(
    title: 'Directory membership',
    config: directoryConfig,
    initialSelectedIds: directory.toList(),
    onChange: (delta, notifyParent) { /* write directory */ },
  ),
  SubPickerTile<Person>(
    title: 'Watchlist',
    config: watchlistConfig,
    initialSelectedIds: watchlist.toList(),
    onChange: (delta, notifyParent) { /* write watchlist */ },
  ),
],''',
  'unrelated-nested-sublist-inside-sublist': r'''SubPickerTile<Person>(
  title: 'Directory membership',
  config: directoryConfig,
  initialSelectedIds: directory.toList(),
  onChange: (delta, notifyParent) { /* write directory */ },
  headerBuilder: (context, directoryController, items) => [
    SubPickerTile<Person>(
      title: 'Favorites',
      config: favoritesConfig,
      initialSelectedIds: favorites.toList(),
      onChange: (delta, notifyParent) { /* write favorites */ },
    ),
  ],
);''',
  'unrelated-child-is-single-optional': r'''SubPickerTile<Person>(
  title: 'Directory membership',
  config: directoryConfig,
  initialSelectedIds: directory.toList(),
  selectionMode: SelectionMode.singleOptional,
  onChange: (delta, notifyParent) { /* write directory */ },
);''',
  'unrelated-child-blocks-in-use': r'''SubPickerTile<Person>(
  title: 'Directory membership',
  config: peopleConfig(
    relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
      unselectPolicy: person.inUse || parent.pendingIds.contains(person.id)
          ? PickerUnselectPolicy.blocked
          : PickerUnselectPolicy.allow,
    ),
    relatedListItemStatusListenable: parent.pendingIdsListenable,
  ),
  initialSelectedIds: directory.toList(),
  onChange: (delta, notifyParent) { /* write directory */ },
);''',
  'unrelated-child-confirms-unselect': r'''SubPickerTile<Person>(
  title: 'Directory membership',
  config: peopleConfig(
    relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
      unselectPolicy: person.inUse || parent.pendingIds.contains(person.id)
          ? PickerUnselectPolicy.confirm
          : PickerUnselectPolicy.allow,
    ),
    relatedListItemStatusListenable: parent.pendingIdsListenable,
  ),
  initialSelectedIds: directory.toList(),
  onChange: (delta, notifyParent) { /* write directory */ },
);''',
  'unrelated-child-with-inactive-rows': r'''SubPickerTile<Person>(
  title: 'Directory membership',
  config: peopleConfig(
    title: 'Directory',
    relatedListItemStatusOf: (person) =>
        PickerRelatedListItemStatus(selectable: !person.locked),
  ),
  initialSelectedIds: directory.toList(),
  onChange: (delta, notifyParent) { /* write directory */ },
);''',
  'unrelated-sublist-plus-related-list-icons': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
      auxiliaryMembership: directory.contains(person.id)
          ? PickerAuxiliaryMembership.member
          : PickerAuxiliaryMembership.notMember,
    ),
  ),
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory membership',
      config: directoryConfig,
      initialSelectedIds: directory.toList(),
      onChange: (delta, notifyParent) { /* write directory */ },
    ),
  ],
);''',
  'unrelated-parent-close-child-change': r'''SearchAnchorPicker<Person>(
  onClose: (result) { /* write selected */ },
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory membership',
      config: directoryConfig,
      initialSelectedIds: directory.toList(),
      onChange: (delta, notifyParent) { /* write directory */ },
    ),
  ],
);''',
  'unrelated-parent-change-nested-independent': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'People'),
  initialSelectedIds: selected.toList(),
  onChange: (delta) { /* write selected */ },
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory membership',
      config: directoryConfig,
      initialSelectedIds: directory.toList(),
      onChange: (delta, notifyParent) { /* write directory */ },
    ),
  ],
);''',
  'direct-mirror-plus-parent-onchange': r'''SearchAnchorPicker<Person>(
  onChange: (delta) { /* parent row/bulk only */ },
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      parentController: controller,
      parentSelectionEffect: SubPickerParentSelectionEffect.mirror,
      onChange: (delta, notifyParent) {
        /* write directory */
        notifyParent();
      },
    ),
  ],
);''',
  'api-fail-close': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'API fail close'),
  initialSelectedIds: selected.toList(),
  onClose: (result) async {
    await Future<void>.delayed(const Duration(milliseconds: 700));
    if (result.isEmpty) return;
    if (failClose) throw StateError('simulated onClose failure');
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
  },
);''',
  'api-fail-change': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(title: 'API fail change'),
  initialSelectedIds: selected.toList(),
  onChange: (delta) async {
    await Future<void>.delayed(const Duration(milliseconds: 500));
    if (failChange) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('API fail change')),
      );
      throw StateError('simulated onChange failure');
    }
    selected
      ..addAll(delta.added)
      ..removeAll(delta.removed);
  },
);''',
  'api-fail-search': r'''SearchAnchorPicker<Person>(
  initialSelectedIds: selected.toList(),
  initialSelectedItemCache: cachedPeople,
  onClose: (result) { /* persist result.added / result.removed */ },
);

PickerConfig<Person>(
  itemsLoader: (_, query) async {
    await Future<void>.delayed(const Duration(milliseconds: 500));
    if (failSearch) throw StateError('simulated search API failure');
    return api.searchPeople(query);
  },
);''',
  'api-fail-close-custom-dialog': r'''SearchAnchorPicker<Person>(
  onClose: (result) {
    if (result.isEmpty) return;
    throw StateError('simulated onClose failure');
  },
  closeSaveFailedBuilder: (context, error, stackTrace) async {
    // Overlay prompt with Keep editing / Close without saving
    return CloseSaveFailedAction.updateSelection;
  },
);''',
  'hidden-selected':
      r'''// The app keeps the old initial selection. itemsLoader still returns only
// the page. Inject kept people who are not on that page.
final page = await itemsLoader(context, query);
final pageIds = page.map((person) => person.id).toSet();
final hidden = keptInitialItems.where(
  (person) => !pageIds.contains(person.id),
);

List<Person> load() {
/*bold=on*/  switch (mode) {
    case HiddenItemsMode.inList:
      return [...page, ...hidden];
    case HiddenItemsMode.onlyIfSelected:
      return [
        ...page,
        ...hidden.where((person) => selected.contains(person.id)),
      ];
    case HiddenItemsMode.section:
    case HiddenItemsMode.none:
      return page;
  }
/*bold=off*/}

SearchAnchorPicker<Person>(
  initialSelectedIds: selected.toList(),
  initialSelectedItemCache: /*bold=on*/ mode == HiddenItemsMode.section
      ? keptInitialItems
      : null, /*bold=off*/
  itemBuilder: (context, person, selected, status, source, toggle) {
    final fromCache =
        source == PickerItemSource.initialSelectedItemCache ||
        hidden.any((item) => item.id == person.id);
/*bold=on*/    final keptIcon = fromCache ? Icons.bookmark_outline : Icons.person;
/*bold=off*/    return DefaultPickerItemTile(
      selected: selected,
      relatedListItemStatus: status,
      onToggle: (_) => toggle(),
      title: Text(person.name),
      subtitle: Text(
        fromCache ? '${person.team} · not from itemsLoader' : person.team,
      ),
      leading: Icon(keptIcon),
      selectionMode: SelectionMode.multi,
    );
  },
  onClose: (result) {
    selected
      ..addAll(result.added)
      ..removeAll(result.removed);
    // keptInitialItems stays the original list, so In list still injects
    // Radia after she is unchecked.
  },
);''',
  'related-list-unknown': r'''SearchAnchorPicker<Person>(
  config: peopleConfig(
    relatedListItemStatusOf: (person) => PickerRelatedListItemStatus(
      auxiliaryMembership: directory.contains(person.id)
          ? PickerAuxiliaryMembership.member
          : PickerAuxiliaryMembership.unknown,
    ),
  ),
  headerBuilder: (context, controller, items) => [
    SubPickerTile<Person>(
      title: 'Directory',
      initialSelectedIds: directory.toList(),
      onClose: (result) {
        writeDirectory(result);
        selected.addAll(result.added);
        controller.syncPending(added: result.added);
      },
    ),
  ],
);''',
  'server-search-default-search-field': r'''final debounce = Debouncer();

Future<List<Person>> searchPeople(String query) {
  if (query.isEmpty) return api.searchPeople(query);
  return debounce.run(() => api.searchPeople(query));
}

SearchAnchorPicker<Person>(
  initialSelectedIds: selected.toList(),
  initialSelectedItemCache: cachedPeople,
  onClose: (result) { /* persist result.added / result.removed */ },
);

PickerConfig(
  searchMode: PickerSearchMode.remote,
  itemsLoader: (context, query) => searchPeople(query),
);''',
};
